export const APP_TITLE = '창녕 2호기 Smart Factory';

export const NOTICE_TITLE = '작업자 주의사항';
export const NOTICE_TEMP_THRESHOLD = '580°C';
export const NOTICE_BODY_PREFIX = 'SPOT 온도가 ';
export const NOTICE_BODY_SUFFIX = ' 이상일 경우 즉시 관리자에게 알림.';
export const NOTICE_FOOTER = '외관/센서 조정 상태를 수시로 확인하십시오.';

export const SPOT_UNIT = '°C';

// UI Main Labels
export const LABELS = {
  DASHBOARD: '대시보드',
  SETTINGS: '설정',
  EDIT_LAYOUT: '레이아웃 편집',
  SAVE_LAYOUT: '저장',
  RESTORE_LAYOUT: '복구',
  OBSERVABILITY: '관측성',
  LOG_DRAWER: '로그',
  RETRY: '재시도',
  EXIT: '종료',
  SAVE: '저장',
  CLOSE: '닫기',
  CANCEL: '취소',
  CONFIRM: '확인',
  DELETE: '삭제',
  EDIT: '편집',
  VIEW: '보기',
  LAST_UPDATE: '마지막 갱신',
  THRESHOLD: '임계',
  THRESHOLDS: '임계값',
  SAVE_SNAPSHOT: '스냅샷 저장',
  SPOT_CAMERA: 'SPOT 카메라',
  CONTAINER_FRONT: '콘테이너 앞',
  CONTAINER_BACK: '콘테이너 뒤',
  BILLET_TEMP: '빌렛 온도',
  BILLET_LEN: '빌렛 길이',
  ENV_TEMP: '환경 온도',
  ENV_HUMID: '환경 습도',
  SPEED: '속도',
  PRESS: '압력',
  SPOT: 'SPOT',
  TEMP_F: '온도(F)',
  TEMP_B: '온도(B)',
  COUNT: '생산 수량',
  END_POS: '종료 위치',
  SUMMARY: '요약',
  SUMMARY_INFO: '요약 정보',
  CENTRAL_CONFIG: '중앙 설정',
  COMM_CONFIG: '통신 설정',
  OPER_OBSERVABILITY: '운영/관측성',
  STORAGE_CONFIG: '저장 설정',
  LOG_ROTATION: '로그 회전',
  ALERTS_THRESHOLDS: '알림/임계값',
  SECURITY: '보안',
  APPLY_DETAIL: '적용 상세',
  IMMEDIATE_APPLY: '즉시 적용',
  RESTART_REQUIRED: '재시작 필요',
  NONE: '없음',
  PENDING_SAVE: '보류된 설정 저장',
  PENDING: '보류',
  CREATED: '생성',
  SOURCE: '출처',
  REASON: '사유',
  PATH: '경로',
  APPLY_PENDING: '보류 적용',
  DELETE_PENDING: '보류 삭제',
  CONFIG_PATH: '설정 경로',
  SYNC_STATUS: '동기화 상태',
  SYNC_RUN: '동기화 실행',
  SYNCING: '동기화 중...',
  SERVER: '서버',
  DEVICE: '디바이스',
  LAST_RUN: '마지막 실행',
  MESSAGE: '메시지',
  CONNECTED: '연결됨',
  DISCONNECTED: '끊김',
  TESTING: '테스트 중...',
  COMM_TEST: '연결 테스트',
  METRIC_LOG: '메트릭 로그',
  COPY_PATH: '경로 복사',
  OPEN_FOLDER: '폴더 열기',
  OPEN_FILE: '파일 열기',
  EVENT_SUMMARY: '최근 이벤트 요약',
  LAST_DISCONNECT: '최근 끊김',
  LAST_RECOVERY: '최근 복구',
  RECOVERY_TIME: '복구 시간',
  RECOVERY_COUNT: '복구 횟수',
  CURRENT_DOWNTIME: '현재 다운타임',
  TOTAL_DOWNTIME: '누적 다운타임',
  CONNECT_FAIL: '연결 실패',
  READ_FAIL: '읽기 실패',
  INVALID_RESP: '무효 응답',
  SKIP_READ: '스킵',
  FAIL_TOTAL: '실패 합계',
  BACKOFF: '백오프',
  NEXT_RETRY: '다음 재시도',
  LAST_SUCCESS: '최근 성공',
  LAST_ERROR: '최근 오류',
  MERGE_BLOCKS: '블록 병합',
  MERGE_FAIL: '병합 실패',
  READY: '준비됨',
  EXPORT: '내보내기',
  EXPORTING: '내보내는 중...',
  WINDOW_METRICS: '윈도 지표',
  NORMAL: '정상',
  WARNING: '주의',
  ERROR_QUEUE: '에러 큐',
  OCCURRED: '발생',
  REFRESH: '새로고침',
  CLEAR: '비우기',
  LOADING: '불러오는 중...',
  ERROR_QUEUE_DETAIL: '에러 큐 상세',
  NO_ERROR: '에러 없음',
  BROWSER_ERROR: '브라우저 오류',
  NO_BROWSER_ERROR: '브라우저 오류 없음',
  IMAGE_STATUS: '이미지 상태',
  CONNECTING: '연결 중',
  DELAYED: '지연',
  LAST_RECEIVE: '마지막 수신',
  NOT_RECEIVED: '미수신',
  NO_PREVIEW: '미리보기 없음',
  LOADING_IMAGE: '이미지 로딩 중...',
  AUTO_SAVE_USE: '자동 저장 사용',
  CHECKING: '검사 중...',
  CHECK: '검사',
  CREATE_FOLDER: '폴더 생성',
  UNIT_CASES: '건',
};

// Status Indicators
export const STATUS = {
  RUNNING: '가동 중',
  OFFLINE: '오프라인',
  ERROR: '오류',
  UNKNOWN: '알 수 없음',
  IDLE: '유휴',
  NORMAL: '정상',
  WARNING: '경고',
  DANGER: '위험',
  SET: '설정됨',
  NOT_SET: '미설정',
};

// Form Labels
export const CONFIG_LABELS = {
  LOG_PATH: '로그 경로',
  SNAPSHOT_PATH: '스냅샷 경로',
  AUTO_SAVE: '자동 저장',
  PASSWORD_SET: '비밀번호 설정',
  ROTATION: '로그 회전',
  ROTATION_MODE: '회전 모드',
  CYCLE_IDLE: '사이클 유휴 시간',
  CYCLE_PRESS: '사이클 압력 임계값',
  COLLECT_INTERVAL: '수집 주기',
  SPOT_IP: 'SPOT IP',
  SPOT_URL: 'SPOT URL',
  SPOT_IMG_URL: 'SPOT 이미지 URL',
  SPOT_REFRESH: 'SPOT 갱신 주기',
  CROSSHAIR: 'SPOT 크로스헤어',
  ACTUATOR: '액추에이터',
  LS_PLC: 'LS PLC',
  EXTRUDER: 'Extruder',
  THRESHOLDS: '임계값 설정',
  SPOT_CROSSHAIR_X: 'SPOT 크로스헤어 X',
  SPOT_CROSSHAIR_Y: 'SPOT 크로스헤어 Y',
  SPOT_CROSSHAIR_COLOR: 'SPOT 크로스헤어 색상',
  SPOT_CROSSHAIR_THICKNESS: 'SPOT 크로스헤어 두께',
  SPOT_CROSSHAIR_SIZE: 'SPOT 크로스헤어 크기',
  SPOT_CROSSHAIR_GAP: 'SPOT 크로스헤어 간격',
  SPOT_FOCUS_URL: 'SPOT 포커스 URL',
  SPOT_FOCUS_STEP: 'SPOT 포커스 스텝',
  SPOT_ACTUATOR_IP: 'SPOT 액추에이터 IP',
  SPOT_ACTUATOR_STEP: 'SPOT 액추에이터 스텝',
  SPOT_ACTUATOR_URL: 'SPOT 액추에이터 URL',
  SPOT_WIDGET_WIDTH: 'SPOT 위젯 너비',
  SPOT_WIDGET_HEIGHT: 'SPOT 위젯 높이',
  EXTRUDER_IP: 'Extruder IP',
  EXTRUDER_PORT: 'Extruder Port',
  LS_PLC_IP: 'LS PLC IP',
  LS_PLC_PORT: 'LS PLC Port',
  LS_PLC_TARGETS: 'LS PLC 타깃 매핑',
  CSV_HEADER: 'CSV 헤더',
  ROTATION_ENABLED: '로그 회전 사용',
  THRESHOLD_ENABLE_PREFIX: '임계값 사용',
  THRESHOLD_VALUE_PREFIX: '임계값 값',
};

// Messages
export const MESSAGES = {
  SAVE_SUCCESS: '설정이 저장되었습니다.',
  SAVE_FAILURE: '설정 저장에 실패했습니다.',
  NOTICE_SAVE_FAILURE: '공지 저장에 실패했습니다.',
  DELETE_WIDGET: '위젯을 삭제하시겠습니까?',
  AUTH_REQUIRED: '인증이 필요합니다.',
  VERSION: '버전',
  LAST_SYNC: '최근 동기화',
  LOADING_DATA: '데이터 로딩 중...',
  SYNC_SUCCESS: '중앙 설정이 적용되었습니다.',
  SYNC_NO_CHANGE: '중앙 설정 변경 없음.',
  SYNC_SKIPPED: '로컬 오버라이드로 인해 적용이 보류되었습니다.',
  SYNC_DISABLED: '중앙 설정이 설정되지 않았습니다.',
  SYNC_FAILURE: '중앙 설정 동기화 실패.',
  SYNC_FAILURE_DETAIL: '중앙 설정 동기화에 실패했습니다.',
  INVALID_FORMAT: 'IP/Port 형식을 확인하세요.',
  WAITING_COMM_METRICS: '통신 메트릭 수집 대기 중입니다.',
};
